ImageMajik/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :albums, shallow: true do
    resources :images
  end

  root to: 'splash#default'

  get '/homepage', to: 'homepage#welcome', as: :homepage

  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end

  get '/share/:image_id', to: 'sharing#new', as: :share
  post '/share/:image_id', to: 'sharing#create'
  delete '/share/:user_id', to: 'sharing#destroy'

end

ImageMajik/app/models/album.rb
class Album < ActiveRecord::Base

	belongs_to :user
	has_many :images
	       
end

ImageMajik/app/models/image.rb
class Image < ActiveRecord::Base
	
	belongs_to :album
	has_many :shares

	def user
		album.user
	end

	def share_with(giver, receiver)
		shares.create(image_id: self.id, 
									giver_id: giver.id, 
									receiver_id: receiver.id)
	end

	mount_uploader :picture, PictureUploader
end

ImageMajik/app/models/share.rb
class Share < ActiveRecord::Base

	belongs_to :image

end

ImageMajik/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
 	has_many :albums

 	include Amistad::FriendModel

 	def full_name
  	"#{self[:first_name]} #{self[:last_name]}"
	end
 
end

ImageMajik/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.where(user_id: current_user.id)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user
    if @album.save
      redirect_to @album, notice: "New Album Created"
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      redirect_to @album, notice: "Successfully Deleted"
    end
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      temp = {"user_id" => current_user.id()}
      params.merge(temp)
      params.require(:album).permit(:title, :user_id)
    end
end

ImageMajik/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :authenticate_user!, only: [:welcome]

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :account_name]
  end

end

ImageMajik/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

before_filter :authenticate_user!

  def index
    @friends = current_user.friends
    @other_invited = current_user.pending_invited_by
    @you_invited = current_user.pending_invited
  end

  def new
    @users = User.where(["id != :this", {this: current_user.id}])
    @not_connected = Array.new()
    @users.each do |user|
      if current_user.connected_with? user
        # Do nothing
      else 
        @not_connected << user
      end
    end
  end

  def create
    invitee = User.find_by_id(params[:user_id])
    if current_user.invite invitee
      redirect_to new_friend_path, :notice => "Successfully invited user!"
    else
      redirect_to new_friend_path, :notice => "Sorry! You can't invite that user!"
    end
  end

  def update
    inviter = User.find_by_id(params[:id])
    if current_user.approve inviter
      redirect_to friends_path, :notice => "Successfully confirmed friendship!"
    else
      redirect_to friends_path, :notice => "Sorry! Could not confirm friendship!"
    end
  end

  def requests
    @pending_requests = current_user.pending_invited_by
  end

  def invites
    @pending_invites = current_user.pending_invited
  end

  def destroy
    user = User.find_by_id(params[:id])
    if current_user.remove_friendship user
      redirect_to friends_path, :notice => "Successfully removed friend!"
    else
      redirect_to friends_path, :notice => "Sorry, couldn't remove friend!"
    end
  end

end

ImageMajik/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :authenticate_user!, only: [:welcome]

  def welcome
  	@albums = Album.where(user_id: current_user.id)
    @friends = current_user.friends
    @shared_images = Share.where("receiver_id = ?", params[:current_user_id])
  end

end

ImageMajik/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :set_album, only: [:index, :new, :create]

  def index
    @images = Image.where(user_id: current_user.id)
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def edit
    @image = Image.find(params[:id])
  end

  def create
    @image = Image.new(image_params)
    @image.album = @album
    if @image.save
      redirect_to @image, notice: "New Image Created"
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      redirect_to @image.album, notice: "Successfully Deleted"
    end
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def set_album
      @album = Album.find(params[:album_id])
    end

    def image_params
      params.require(:image).permit(:label, :caption, :picture)
    end
end

ImageMajik/app/controllers/sharing_controller.rb
class SharingController < ApplicationController
  before_action :authenticate_user!

  def new
  	@image = Image.find_by_id(params[:image_id])
  	@shareable_with = current_user.friends
  end

  def create
    image = Image.find_by_id(params[:image_id])
    user = User.find_by_id(params[:user_id])
    if image.share_with(current_user, user)
      redirect_to share_path, :notice => "Successfully shared image!"
    else
      redirect_to share_path, :notice => "Sorry! Unable to share image with that user!"
    end
  end

  def destroy
    # user = Image.find_by_id(params[:user_id])
    # if current_user.remove_friendship user
    #   redirect_to friends_path, :notice => "Successfully removed friend!"
    # else
    #   redirect_to friends_path, :notice => "Sorry, couldn't remove friend!"
    # end
  end

end

ImageMajik/app/controllers/splash_controller.rb
class SplashController < ApplicationController

  def default
    if user_signed_in?
      redirect_to homepage_path
    end
  end

end

ImageMajik/app/helpers/albums_helper.rb
module AlbumsHelper
end

ImageMajik/app/helpers/application_helper.rb
module ApplicationHelper
end

ImageMajik/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

ImageMajik/app/helpers/images_helper.rb
module ImagesHelper
end

ImageMajik/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ImageMajik/app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', @album %>

ImageMajik/app/views/albums/index.html.erb
<h1>Current Albums</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
</table>
  <body>
    <% @albums.each do |album| %>
      <br>
        <p><%= link_to album.title, album %></p>
        <p><%= link_to 'Edit', edit_album_path(album) %></p>
        <p><%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <br>
    <% end %>
  
  <p><%= link_to 'New Album', new_album_path %></p>
  <p><%= link_to 'Back', homepage_path %></p>

  </body>


<br>

ImageMajik/app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

ImageMajik/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album Title:</strong>
  <%= @album.title %>
</p>

<p><%= link_to 'Edit', edit_album_path(@album) %> |
	<%= link_to 'Back', albums_path %>
</p>

<body>
  <div id="images">
    <% @album.images.each do |image| %>
      <br>
        <div class="image">
          <%= image_tag image.picture_url(:thumb).to_s %>
          <p><strong>Label:</strong>
            <%= link_to image.label, image %></p>
          <p><strong>Caption:</strong>
            <%= image.caption %></p>
          <p><%= link_to 'Edit', edit_image_path(image) %>
            <%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        </div>
      <br>
    <% end %>
  </div>
</body>

<p><%= link_to 'Add Image', new_album_image_path(@album) %></p>

ImageMajik/app/views/friendships/index.html.erb
<h1> Your Social Network </h1>
<br>

<div class="block">
	<p><strong>Your current friends</strong></p>
	<div>
		<% @friends.each do |friend| %>
			<div class="inline">
				<div class="thumb_placeholder">
					<%= friend.account_name %>
				</div>
				<p><%= link_to "Remove friend?", friend_path(friend), :method => "delete" %></p>
			</div>
		<% end %>
	</div>
</div>

<div class="block">
	<p><strong>Your pending friend requests</strong></p>
	<div>
		<% @you_invited.each do |invited| %>
			<div class="inline">
				<div class="thumb_placeholder">
					<%= invited.account_name %>
				</div>
				<p><%= link_to "Cancel request?", friend_path(invited), :method => "delete" %></p>
			</div>
		<% end %>
	</div>
</div>

<div class="block">
	<p><strong>Waiting for your approval</strong></p>
	<div>
		<% @other_invited.each do |inviter| %>
			<div class="inline">
				<div class="thumb_placeholder">
					<%= inviter.account_name %>
				</div>
				<p><%= link_to "Confirm friend?", friend_path(inviter), :method => "put" %></p>
				<p><%= link_to "Decline request?", friend_path(inviter), :method => "delete" %></p>
			</div>
		<% end %>
	</div>
</div>

<p><%= flash[:notice] %></p>
<br>
<p><%= link_to 'Back', homepage_path %></p>

ImageMajik/app/views/friendships/new.html.erb
<h1> Search for Another User </h1>
<br>

<% @not_connected.each do |user| %>
	<div class="thumb_placeholder">
		<%= user.account_name %>
	</div>
	<p><%= link_to "Add friend?", friends_path(:user_id => user), :method => "post" %></p>
<% end %>

<p><%= flash[:notice] %></p>
<br>
<p><%= link_to 'Back', homepage_path %></p>

ImageMajik/app/views/homepage/_digest.html.erb
<br>
<div id="album-digest">
	<% @albums.each do |album| %>
	  <div class="inline">
		  <p><%= link_to album.title, album %></p>
		  <% album.images.each do |image| %>
		      <p><%= image_tag image.picture_url(:thumb).to_s %>
		      <p><%= link_to image.label, image %></p>
		      <p><%= image.caption %></p>
		  <% end %>
		</div>
	<% end %>
</div>

ImageMajik/app/views/homepage/_feed.html.erb
<br>
<div id="feed">
	<% @shared_images.each do |image| %>
	  <div class="inline">
	      <p><%= image_tag image.picture_url(:thumb).to_s %>
	      <p><%= link_to image.label, image %></p>
	      <p><%= image.caption %></p>
	      <p><%= image.user %></p>
		</div>
	<% end %>
</div>

ImageMajik/app/views/homepage/_friends.html.erb
<div id="friends-digest">	
	<% @friends.each do |friend| %>
		<div class="inline">
			<div class="thumb_placeholder">
				<%= friend.account_name %>
			</div>
		</div>
	<% end %>
</div>

ImageMajik/app/views/homepage/welcome.html.erb
<h1> <%="#{current_user.account_name}'s Homepage "%></h1>

<div id="friends-list" class="block">
	<p><%= link_to 'Find other Friends', new_friend_path %> |
		<%= link_to 'Manage Friendships', friends_path %></p>
	<%= render 'friends' %>
</div>
<div id="newsfeed" class="block col-md-6">
	<p><strong>Your Newsfeed</strong></p>
	<%= render 'feed' %>
</div>
<div id="album-display" class="block col-md-5">
	<p><%= link_to 'Manage Your Albums', albums_path %></p>
	<%= render 'digest' %>
</div>

ImageMajik/app/views/images/_form.html.erb
<%= form_for [@album, @image], :html => {:multipart => true} do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.file_field :picture %><br>
  </div>
  <div>
    <%= f.label :remote_picture_url, "or image URL" %>
    <%= f.text_field :remote_picture_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ImageMajik/app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', @image %>

ImageMajik/app/views/images/index.html.erb
<h1>Current Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
</table>
  <body>
    <% @images.each do |image| %>
      <br>
        <p><%= link_to image.label, image %></p>
        <p><%= link_to 'Edit', edit_image_path(image) %></p>
        <p><%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <br>
    <% end %>
  </body>


<br>

<p><%= link_to 'Add New Image', new_image_path %></p>
<p><%= link_to 'Back', albums_path %></p>

ImageMajik/app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', @album %>

ImageMajik/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<%= image_tag @image.picture_url(:thumb).to_s %>
</p>
<p>
  <strong>Label:</strong>
  <%= @image.label %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @image.caption %>
</p>

<%= link_to 'Share', share_path(@image) %> |
<%= link_to 'Edit', edit_image_path %> |
<%= link_to 'Back', album_path(@image.album) %>

ImageMajik/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageMajik</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
      <div class="container">
        <%= link_to "ImageMajik", root_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="navbar-links">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
        </div>
      </div>  
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>
  <p class="alert"><%= alert %></p>
</body>
</html>

ImageMajik/app/views/sharing/new.html.erb
<h2>This is the sharing interface!<h2>

<div id="sharing">
	<% @shareable_with.each do |user| %>
		<div class="inline">
			<div class="thumb_placeholder">
				<%= user.account_name %>
			</div>
			<p><%= link_to "Share with?", share_path(:image_id => @image, :user_id => user), :method => "post" %></p>
		</div>
	<% end %>
</div>

<p><%= flash[:notice] %></p>
<br>
<p><%= link_to 'Back', image_path(@image) %></p>

ImageMajik/app/views/splash/default.html.erb
<h1>Welcome to ImageMajik!</h1>